export const SET_MENU_OPEN = 'sujin/v1/SET_MENU_OPEN'
export const SET_DELETE_MODAL = 'sujin/v1/SET_DELETE_MODAL'
export const SET_UPDATE_MODAL = 'sujin/v1/SET_UPDATE_MODAL'
export const CLOSE_MODAL = 'sujin/v1/CLOSE_MODAL'
export const SET_CALLOUT = 'sujin/v1/SET_CALLOUT'
