export const SET_MENU_OPEN = 'sujin/v1/SET_MENU_OPEN'
export const SET_DELETE_MODAL = 'sujin/v1/SET_DELETE_MODAL'
export const SET_UPDATE_MODAL = 'sujin/v1/SET_UPDATE_MODAL'
export const SET_ADD_MODAL = 'sujin/v1/SET_ADD_MODAL'
export const SET_CATEGORY_SELECTOR = 'sujin/v1/SET_CATEGORY_SELECTOR'
export const CLOSE_MODAL = 'sujin/v1/CLOSE_MODAL'
export const SET_CALLOUT = 'sujin/v1/SET_CALLOUT'
